# Notebook Orquestador del Pipeline de Credit Risk
Este notebook permite ejecutar **todo el flujo MLOps** del proyecto:
- Carga de configuración
- Lectura de datos
- Exploración inicial
- Entrenamiento de modelos (XGBoost, Regresión Logística, MLP)
- Registro automático en MLflow

In [5]:
import sys
import os

current_dir = os.getcwd()
project_root = os.path.dirname(current_dir)

if project_root not in sys.path:
    sys.path.append(project_root)

In [30]:
%load_ext autoreload
%autoreload 2

In [15]:
import yaml
import mlflow
import pandas as pd
from src.models.train import train_all_models
from src.data.load_data import load_raw_data

with open(f'{project_root}/configs/config.yaml', 'r') as f:
    cfg = yaml.safe_load(f)

cfg

{'data': {'path': '/teamspace/studios/this_studio/data/raw/credit.csv',
  'target_col': 'default'},
 'training': {'test_size': 0.3,
  'random_state': 42,
  'experiment_name': 'credit_risk_experiment'}}

In [24]:
df = load_raw_data(cfg['data']['path'])
df.head()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone,default
0,< 0 DM,6,critical,furniture/appliances,1169,unknown,> 7 years,4,4,67,none,own,2,skilled,1,yes,no
1,1 - 200 DM,48,good,furniture/appliances,5951,< 100 DM,1 - 4 years,2,2,22,none,own,1,skilled,1,no,yes
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 years,2,3,49,none,own,1,unskilled,2,no,no
3,< 0 DM,42,good,furniture/appliances,7882,< 100 DM,4 - 7 years,2,4,45,none,other,1,skilled,2,no,no
4,< 0 DM,24,poor,car,4870,< 100 DM,1 - 4 years,3,4,53,none,other,2,skilled,2,no,yes

In [38]:
from src.features.preprocessing import build_preprocessor
from src.features.feature_selection import HybridFeatureSelector

target = cfg["data"]["target_col"]
preprocessor = build_preprocessor(df, target)

df[target] = df[target].replace({'no': 0, 'yes': 1})

X = df.drop(columns=[target])
y = df[target]

# --- Transformar X a matriz numérica ---
X_processed = preprocessor.fit_transform(X)

# Recuperar nombres de columnas después del Ordinal
cat_cols = preprocessor.transformers_[1][2]   # las columnas categóricas originales
num_cols = preprocessor.named_transformers_["num"].feature_names_in_
feature_names = list(num_cols) + list(cat_cols)

In [39]:
feature_names

['months_loan_duration',
 'amount',
 'percent_of_income',
 'years_at_residence',
 'age',
 'existing_loans_count',
 'dependents',
 'checking_balance',
 'credit_history',
 'purpose',
 'savings_balance',
 'employment_duration',
 'other_credit',
 'housing',
 'job',
 'phone']

In [40]:
# Convertir a DataFrame para el selector
X_df = pd.DataFrame(X_processed, columns=feature_names)

selector = HybridFeatureSelector(top_k=10)
selector.fit(X_df, y)

pd.DataFrame({"feature": selector.selected_features_})

                feature
0      checking_balance
1  months_loan_duration
2        credit_history
3     percent_of_income
4                 phone
5                amount
6       savings_balance
7          other_credit
8                   age
9               housing

## Entrenar modelos completos con MLflow

In [41]:
mlflow.set_experiment(cfg['training']['experiment_name'])

with mlflow.start_run(run_name='notebook_orchestrator'):
    results = train_all_models(
        data_path=cfg['data']['path'],
        target_col=cfg['data']['target_col'],
        test_size=cfg['training']['test_size'],
        random_state=cfg['training']['random_state']
    )

results

2025/12/08 15:57:56 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/12/08 15:57:56 INFO mlflow.store.db.utils: Updating database tables
2025/12/08 15:57:56 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/08 15:57:56 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade  -> 451aebb31d03, add metric step
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade f5a4f2784254 -> 0584bdc529eb, add cascading deletion to datasets from experiments
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 0584bdc529eb -> 400f98739977, add logged model tables
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 400f98739977 -> 6953534de441, add step to inputs table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 6953534de441 -> bda7b8c39065, increase_model_version_tag_value_limit
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade bda7b8c39065 -> cbc13b556ace, add V3 trace schema columns
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade cbc13b556ace -> 770bee3ae1dd, add assessments table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade 770bee3ae1dd -> a1b2c3d4e5f6, add spans table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade a1b2c3d4e5f6 -> de4033877273, create entity_associations table
2025/12/08 15:57:56 INFO alembic.runtime.migration: Running upgrade de4033877273 -> 1a0cddfcaa16, Add webhooks and webhook_events tables
2025/12/08 15:57:57 INFO alembic.runtime.migration: Running upgrade 1a0cddfcaa16 -> 534353b11cbc, add scorer tables
2025/12/08 15:57:57 INFO alembic.runtime.migration: Running upgrade 534353b11cbc -> 71994744cf8e, add evaluation datasets
2025/12/08 15:57:57 INFO alembic.runtime.migration: Running upgrade 71994744cf8e -> 3da73c924c2f, add outputs to dataset record
2025/12/08 15:57:57 INFO alembic.runtime.migration: Running upgrade 3da73c924c2f -> bf29a5ff90ea, add jobs table
2025/12/08 15:57:57 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2025/12/08 15:57:57 INFO alembic.runtime.migration: Will assume non-transactional DDL.
2025/12/08 15:57:57 INFO mlflow.tracking.fluent: Experiment with name 'credit_risk_experiment' does not exist. Creating a new experiment.
2025-12-08 15:57:57,262 - INFO - Entrenando modelo: logistic_regression
2025-12-08 15:58:00,551 - INFO - Entrenando modelo: xgboost
2025-12-08 15:58:05,479 - INFO - Entrenando modelo: mlp

{'logistic_regression': {'test_auc': 0.7412698412698412,
  'test_accuracy': 0.75,
  'test_f1': 0.4444444444444444,
  'confusion_matrix': [[195, 15], [60, 30]],
  'cv_auc_mean': 0.7255102040816326},
 'xgboost': {'test_auc': 0.7759259259259259,
  'test_accuracy': 0.74,
  'test_f1': 0.49350649350649345,
  'confusion_matrix': [[184, 26], [52, 38]],
  'cv_auc_mean': 0.7573372206025268},
 'mlp': {'test_auc': 0.5458730158730158,
  'test_accuracy': 0.7,
  'test_f1': 0.02173913043478261,
  'confusion_matrix': [[209, 1], [89, 1]],
  'cv_auc_mean': 0.6042759961127309}}